### PR TITLE
Bsdf converter

### PR DESCRIPTION
**Pull request by SandAuriol**
@StefanThoene I'm creating a pull request for the BSDF code.
There is only one unit test that checks that converts a Zemax file into a Speos anisotropicbsdf. It checks the created file with a reference. I will need to add more tests for the other configurations.
But I thought it would be a good start.

### CODE REVIEW

**Comment by SandAuriol** [comment]
I don't know why the pre-commit fails here because it works on my side.

**Comment by pluAtAnsys** [comment]
> I don't know why the pre-commit fails here because it works on my side.

resolved with pre-commit autoupdate

**Comment by SandAuriol** [comment]
Hi @pluAtAnsys! Could you help me with these errors? The unit tests don't pass. Test 12 works on my computer.

**Comment by SandAuriol** [comment]
Hey @StefanThoene! The checks have passed :-)
If you have time to have a look, that would be great. No worries if not.

**Review by StefanThoene — APPROVED** [review]

**Pull request merged**
